[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Adicione estas linhas abaixo
[[plugins]]
package = "@netlify/plugin-functions-install-core"